### PR TITLE
Add base CentOS remote

### LINKED ISSUE #1: include base centos config
So it's easier to rebase back and forth.

### PR DESCRIPTION
**Pull request by miabbott**
Include the remote for the base CentOS tree, so that users can easily
rebase back to the non-continuous tree.

Fixes #1

### CODE REVIEW

**Comment by miabbott** [comment]
Not sure if this the correct way to fix this...@cgwalters let me know.

**Comment by cgwalters** [comment]
It is!  Though there are a few things missing from this:
- Adding the new dir to the `%files` section (yeah RPM sucks)
- Storing the GPG key used in `/usr/share/ostree/trusted.gpg.d`

In general...I'm thinking now what might be saner is to just `cp /ostree/deploy/...<current deployment>/etc/ostree/remotes.d/* $(ostree admin --print-current-dir)/etc` or something.  Perhaps make this nicer as:

```ostree copy-config /etc/ostree/remotes.d/*` ?

We could special case `/etc/ostree/remotes.d` but...

**Comment by miabbott** [comment]
@cgwalters I took a stab at adding the missing pieces, although I admittedly haven't tested any of this

**Comment by cgwalters** [comment]
So right now unfortunately CAHC doesn't have PR testing, so let's merge this tomorrow when I can babysit the CI and see if it works.

**Comment by cgwalters** [comment]
Okay let's try this...

**Comment by cgwalters** [comment]
Nope, https://ci.centos.org/job/atomic-rdgo-centos7/2467/artifact/build-logs/build-logs/failed/centos-release-atomic-host-devel/build.log

**Comment by cgwalters** [comment]
Reverted for now so I can get other things to build.

**Comment by miabbott** [comment]
I think I have the fixes for the build errors.  Should I submit a new PR or just push them here?

**Comment by cgwalters** [comment]
Open a new one please.

**Pull request merged**
